version: '3.8'

services:
  zilla-dam:
    build: .
    container_name: zilla-dam
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: production
      POSTGRES_URL: postgresql://zilla:password@postgres:5432/zilladam
      REDIS_URL: redis://redis:6379
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - zilla-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: zilla
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zilladam
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - zilla-network

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - zilla-network

  monitoring:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - zilla-network

volumes:
  postgres_data:
  redis_data:

networks:
  zilla-network:
    driver: bridge
